### PR TITLE
Add win support and enhance error handling

### PR DESCRIPTION
**Pull request by int3l**
Today I saw this cool script on your stream, but it seems that you didn't push the latest version of it to GitHub,
The latest public version doesn't work without some modifications (because of the GitHub API changes).
Anyways, I guess that you can merge the changes - added Windows support and improved the error handling a bit.

Cheers!

### CODE REVIEW

**Comment by asottile** [comment]
this is all I needed for windows support, want to update your patch?

```diff
diff --git a/python/git-github-fork b/python/git-github-fork
index 33c76b3..2d6f49f 100755
--- a/python/git-github-fork
+++ b/python/git-github-fork
@@ -3,6 +3,7 @@ import argparse
 import json
 import os
 import subprocess
+import sys
 import urllib.request


@@ -17,7 +18,7 @@ def get_slug():
 def load_config():
     filename = os.path.expanduser('~/.github-auth.json')
     mode = os.stat(filename).st_mode & 0o777
-    if mode != 0o600:
+    if sys.platform != 'win32' and mode != 0o600:
         raise SystemExit(
             f'{filename} has too-permissive permissions, Expected 0o600, '
             f'got 0o{mode:o}',
```

**Comment by int3l** [comment]
Yep, this is better. But don't we want the additional error handling too? It helps with the initial setup.

**Comment by int3l** [comment]
Also is there any particular reason for using `sys.platform` over `os.name` other than the better granularity?

**Comment by asottile** [comment]
> 
> 
> Yep, this is better. But don't we want the additional error handling too? It helps with the initial setup.

I'd just leave it, (1) it's unrelated to the change and (2) the error message already contains enough information to infer the same things (the process failure includes the command, the file stat includes the filename)

**Comment by asottile** [comment]
> 
> 
> Also is there any particular reason for using `sys.platform` over `os.name` other than the better granularity?

the only reason I've seen is `mypy` recognizes `sys.platform` but doesn't recognize `os.name` -- otherwise they should be basically the same

I've cataloged some common values for platforms here: https://github.com/asottile/scratch/wiki/platforms

**Pull request merged**
